const BUSINESS_DATA = [{id:"shawarma",name:"Shawarma Stand",cat:"Food",summary:"₦500k-₦1.2m/month near schools",
 startup:{NG:800000}, profit:{NG:350000},
 comp:"The Place, Chicken Republic", 
 beat:"Late night hours + Student discount + Delivery", 
 limit:"NEPA + Meat price increase + NAFDAC", 
 mistake:"Bad location with no foot traffic"},

{id:"amala",name:"Amala & Ewedu Joint",cat:"Food",summary:"₦300k-₦800k/month daily customers",
 startup:{NG:600000}, profit:{NG:250000},
 comp:"Mama Put, Bukas", 
 beat:"Clean environment + Fast service + Soup variety", 
 limit:"Perishable food + Staff wahala", 
 mistake:"Cooking too much and wasting food"},

{id:"smallchops",name:"Small Chops Business",cat:"Food",summary:"₦200k-₦600k/month events",
 startup:{NG:250000}, profit:{NG:180000},
 comp:"Event caterers", 
 beat:"Instagram + Free delivery + Party packages", 
 limit:"Last minute orders + Ingredient cost", 
 mistake:"Not collecting 50% deposit"},

{id:"zobo",name:"Zobo & Tigernut Drink",cat:"Food",summary:"₦150k-₦400k/month wholesale",
 startup:{NG:150000}, profit:{NG:120000},
 comp:"Chi, 5 Alive", 
 beat:"No sugar + Bottled + Supply to gyms", 
 limit:"Short shelf life + Bottles cost", 
 mistake:"Poor hygiene and packaging"},

{id:"fish",name:"Catfish Farming",cat:"Food",summary:"₦1m-₦3m/month after 6 months",
 startup:{NG:2000000}, profit:{NG:800000},
 comp:"Imported fish", 
 beat:"Organic + Supply to restaurants", 
 limit:"Feed cost + Disease + Thieves", 
 mistake:"Overstocking pond"},

{id:"pastries",name:"Meatpie & Sausage Roll",cat:"Food",summary:"₦250k-₦700k/month schools",
 startup:{NG:400000}, profit:{NG:200000},
 comp:"Mr Biggs", 
 beat:"Supermarket supply + School contracts", 
 limit:"Gas cost + Flour price", 
 mistake:"Inconsistent taste"},

{id:"icecream",name:"Ice Cream Cart",cat:"Food",summary:"₦400k-₦1m/month locations",
 startup:{NG:1200000}, profit:{NG:300000},
 comp:"Cold Stone", 
 beat:"Unique flavors + Events + Schools", 
 limit:"Generator + Melting + NEPA", 
 mistake:"Buying big freezer first"},

{id:"rice",name:"Jollof Rice Bowl",cat:"Food",summary:"₦600k-₦1.5m/month delivery",
 startup:{NG:500000}, profit:{NG:400000},
 comp:"Buka, Food vendors", 
 beat:"Online orders + Food app + Consistent taste", 
 limit:"Gas + Rice price + Riders", 
 mistake:"No packaging branding"},

{id:"yoghurt",name:"Greek Yoghurt",cat:"Food",summary:"₦300k-₦900k/month health market",
 startup:{NG:350000}, profit:{NG:220000},
 comp:"Wara, Fanmilk", 
 beat:"No sugar + Fruit toppings + Gym supply", 
 limit:"Fridge + Short expiry", 
 mistake:"Bad sealing causing spoilage"},

{id:"snail",name:"Snail Farming",cat:"Food",summary:"₦800k-₦2m/month export",
 startup:{NG:700000}, profit:{NG:500000},
 comp:"Importers", 
 beat:"Supply to hotels + Export", 
 limit:"Weather + Slow growth", 
 mistake:"Poor housing for snails"},

{id:"cake",name:"Custom Cake Business",cat:"Food",summary:"₦500k-₦1.5m/month birthdays",
 startup:{NG:600000}, profit:{NG:350000},
 comp:"Bakeries", 
 beat:"Instagram + 24hr rush order + Delivery", 
 limit:"Oven + Ingredients + Last minute", 
 mistake:"No deposit before baking"},

{id:"plantain",name:"Fried Plantain & Fish",cat:"Food",summary:"₦400k-₦900k/month evenings",
 startup:{NG:300000}, profit:{NG:200000},
 comp:"Buka, Street vendors", 
 beat:"Clean shop + Suya spice + Night sales", 
 limit:"Oil price + Plantain waste", 
 mistake:"Single location only"},

{id:"catering",name:"Event Catering",cat:"Food",summary:"₦1m-₦5m/month weddings",
 startup:{NG:1000000}, profit:{NG:600000},
 comp:"Big caterers", 
 beat:"Tasting + Payment plan + Decor package", 
 limit:"Staff + Equipment rental", 
 mistake:"Underpricing to get client"},

{id:"smoothie",name:"Smoothie Bar",cat:"Food",summary:"₦350k-₦800k/month gyms",
 startup:{NG:900000}, profit:{NG:250000},
 comp:"Juice bars", 
 beat:"Healthy + Gym partnership + App", 
 limit:"Fruits cost + Blender + NEPA", 
 mistake:"Expensive location too early"},

{id:"pepper",name:"Pepper Soup Spot",cat:"Food",summary:"₦500k-₦1.2m/month night",
 startup:{NG:450000}, profit:{NG:300000},
 comp:"Buka, Beer parlour", 
 beat:"Late night + Goat meat + Live music", 
 limit:"Security + Meat supply", 
 mistake:"No generator backup"}
  // NIGERIA DATA FIRST
  {id:"pos",name:"POS Business",cat:"Finance",
   startup:{NG:350000}, profit:{NG:150000},
   comp:"Opay, Moniepoint, Banks", 
   beat:"Lower charges + Fast network + Agent banking", 
   limit:"Network downtime + Cash float + Fraud", 
   mistake:"Not securing shop with CCTV"},
  
  {id:"coffee",name:"Coffee Shop",cat:"Food",
   startup:{NG:12000000}, profit:{NG:800000},
   comp:"Local bukas, Starbucks", 
   beat:"Generator + Delivery + Student discounts", 
   limit:"NEPA + Fuel + Imported beans", 
   mistake:"Depending on one generator"},

  // AMERICA DATA
  {id:"pos",name:"ATM Business",cat:"Finance", // In US na ATM, not POS
   startup:{US:8000}, profit:{US:1200},
   comp:"Banks, Chime", 
   beat:"Place in gas stations + No fees", 
   limit:"Cash restocking + Vandalism", 
   mistake:"Bad location"},

  {id:"coffee",name:"Coffee Shop",cat:"Food",
   startup:{US:50000}, profit:{US:10000},
   comp:"Starbucks, Dunkin", 
   beat:"Drive-thru + Mobile app", 
   limit:"High rent + Labor costs", 
   mistake:"Buying too much equipment"}
];
