const BUSINESS_DATA = [{id:"shawarma",name:"Shawarma Stand",cat:"Food",summary:"₦500k-₦1.2m/month near schools",
 startup:{NG:800000}, profit:{NG:350000},
 comp:"The Place, Chicken Republic", 
 beat:"Late night hours + Student discount + Delivery", 
 limit:"NEPA + Meat price increase + NAFDAC", 
 mistake:"Bad location with no foot traffic"},

{id:"amala",name:"Amala & Ewedu Joint",cat:"Food",summary:"₦300k-₦800k/month daily customers",
 startup:{NG:600000}, profit:{NG:250000},
 comp:"Mama Put, Bukas", 
 beat:"Clean environment + Fast service + Soup variety", 
 limit:"Perishable food + Staff wahala", 
 mistake:"Cooking too much and wasting food"},

{id:"smallchops",name:"Small Chops Business",cat:"Food",summary:"₦200k-₦600k/month events",
 startup:{NG:250000}, profit:{NG:180000},
 comp:"Event caterers", 
 beat:"Instagram + Free delivery + Party packages", 
 limit:"Last minute orders + Ingredient cost", 
 mistake:"Not collecting 50% deposit"},

{id:"zobo",name:"Zobo & Tigernut Drink",cat:"Food",summary:"₦150k-₦400k/month wholesale",
 startup:{NG:150000}, profit:{NG:120000},
 comp:"Chi, 5 Alive", 
 beat:"No sugar + Bottled + Supply to gyms", 
 limit:"Short shelf life + Bottles cost", 
 mistake:"Poor hygiene and packaging"},

{id:"fish",name:"Catfish Farming",cat:"Food",summary:"₦1m-₦3m/month after 6 months",
 startup:{NG:2000000}, profit:{NG:800000},
 comp:"Imported fish", 
 beat:"Organic + Supply to restaurants", 
 limit:"Feed cost + Disease + Thieves", 
 mistake:"Overstocking pond"},

{id:"pastries",name:"Meatpie & Sausage Roll",cat:"Food",summary:"₦250k-₦700k/month schools",
 startup:{NG:400000}, profit:{NG:200000},
 comp:"Mr Biggs", 
 beat:"Supermarket supply + School contracts", 
 limit:"Gas cost + Flour price", 
 mistake:"Inconsistent taste"},

{id:"icecream",name:"Ice Cream Cart",cat:"Food",summary:"₦400k-₦1m/month locations",
 startup:{NG:1200000}, profit:{NG:300000},
 comp:"Cold Stone", 
 beat:"Unique flavors + Events + Schools", 
 limit:"Generator + Melting + NEPA", 
 mistake:"Buying big freezer first"},

{id:"rice",name:"Jollof Rice Bowl",cat:"Food",summary:"₦600k-₦1.5m/month delivery",
 startup:{NG:500000}, profit:{NG:400000},
 comp:"Buka, Food vendors", 
 beat:"Online orders + Food app + Consistent taste", 
 limit:"Gas + Rice price + Riders", 
 mistake:"No packaging branding"},

{id:"yoghurt",name:"Greek Yoghurt",cat:"Food",summary:"₦300k-₦900k/month health market",
 startup:{NG:350000}, profit:{NG:220000},
 comp:"Wara, Fanmilk", 
 beat:"No sugar + Fruit toppings + Gym supply", 
 limit:"Fridge + Short expiry", 
 mistake:"Bad sealing causing spoilage"},

{id:"snail",name:"Snail Farming",cat:"Food",summary:"₦800k-₦2m/month export",
 startup:{NG:700000}, profit:{NG:500000},
 comp:"Importers", 
 beat:"Supply to hotels + Export", 
 limit:"Weather + Slow growth", 
 mistake:"Poor housing for snails"},

{id:"cake",name:"Custom Cake Business",cat:"Food",summary:"₦500k-₦1.5m/month birthdays",
 startup:{NG:600000}, profit:{NG:350000},
 comp:"Bakeries", 
 beat:"Instagram + 24hr rush order + Delivery", 
 limit:"Oven + Ingredients + Last minute", 
 mistake:"No deposit before baking"},

{id:"plantain",name:"Fried Plantain & Fish",cat:"Food",summary:"₦400k-₦900k/month evenings",
 startup:{NG:300000}, profit:{NG:200000},
 comp:"Buka, Street vendors", 
 beat:"Clean shop + Suya spice + Night sales", 
 limit:"Oil price + Plantain waste", 
 mistake:"Single location only"},

{id:"catering",name:"Event Catering",cat:"Food",summary:"₦1m-₦5m/month weddings",
 startup:{NG:1000000}, profit:{NG:600000},
 comp:"Big caterers", 
 beat:"Tasting + Payment plan + Decor package", 
 limit:"Staff + Equipment rental", 
 mistake:"Underpricing to get client"},

{id:"smoothie",name:"Smoothie Bar",cat:"Food",summary:"₦350k-₦800k/month gyms",
 startup:{NG:900000}, profit:{NG:250000},
 comp:"Juice bars", 
 beat:"Healthy + Gym partnership + App", 
 limit:"Fruits cost + Blender + NEPA", 
 mistake:"Expensive location too early"},

{id:"pepper",name:"Pepper Soup Spot",cat:"Food",summary:"₦500k-₦1.2m/month night",
 startup:{NG:450000}, profit:{NG:300000},
 comp:"Buka, Beer parlour", 
 beat:"Late night + Goat meat + Live music", 
 limit:"Security + Meat supply", 
 mistake:"No generator backup"}
                       
 {id:"pos",name:"POS Business",cat:"Finance",summary:"₦100k-₦400k/month transfers",
startup:{NG:350000}, profit:{NG:150000},
comp:"Opay, Moniepoint, Banks", 
beat:"Lower charges + Fast network + Agent banking + Airtime", 
limit:"Network downtime + Cash float + Fraud + Multiple tax", 
mistake:"Not securing shop with CCTV and security"},

{id:"atm",name:"ATM Machine Business",cat:"Finance",summary:"₦200k-₦600k/month locations",
startup:{NG:4500000}, profit:{NG:250000},
comp:"Banks", 
beat:"Place in malls + No withdrawal fee + 24hrs", 
limit:"Cash restocking + Vandalism + CBN license", 
mistake:"Bad location with low traffic"},

{id:"p2p",name:"Crypto P2P Trading",cat:"Finance",summary:"₦500k-₦2m/month arbitrage",
startup:{NG:1000000}, profit:{NG:400000},
comp:"Binance P2P, Bybit", 
beat:"Fast release + Good rate + WhatsApp group", 
limit:"CBN ban + Scammers + Account freeze", 
mistake:"Trading with strangers no escrow"},

{id:"thrift",name:"Ajo/Thrift Collection",cat:"Finance",summary:"₦300k-₦1m/month from 200 people",
startup:{NG:100000}, profit:{NG:200000},
comp:"Banks, PiggyVest", 
beat:"Daily collection + Trust + WhatsApp reminders", 
limit:"Defaulters + Trust issues", 
mistake:"Not keeping proper record"},

{id:"loan",name:"Small Loan App/Agent",cat:"Finance",summary:"₦400k-₦1.5m/month interest",
startup:{NG:2000000}, profit:{NG:600000},
comp:"Fairmoney, Carbon", 
beat:"Fast approval + Low interest + Market women", 
limit:"Defaulters + CAC + CBN regulation", 
mistake:"Lending without collateral/guarantor"},

{id:"forex",name:"Forex Trading",cat:"Finance",summary:"₦200k-₦1m/month trading",
startup:{NG:500000}, profit:{NG:300000},
comp:"Banks, Bureau De Change", 
beat:"Training + Signals group + Low spreads", 
limit:"Volatility + CBN policy + Scam brokers", 
mistake:"Using leverage and no risk management"},

{id:"investment",name:"Investment Club",cat:"Finance",summary:"₦1m-₦5m/month AUM",
startup:{NG:200000}, profit:{NG:350000},
comp:"Treasury Bills, Mutual Funds", 
beat:"Transparency + Monthly ROI + WhatsApp updates", 
limit:"SEC registration + Trust + Market crash", 
mistake:"Promising fixed returns"},

{id:"agent",name:"Bank Agent Banking",cat:"Finance",summary:"₦150k-₦500k/month commissions",
startup:{NG:500000}, profit:{NG:180000},
comp:"Opay, Moniepoint Agents", 
beat:"Multiple banks + POS + Bill payment", 
limit:"Network + Cash + Bank approval", 
mistake:"One bank only"},

{id:"bill",name:"Bill Payment Center",cat:"Finance",summary:"₦80k-₦300k/month bills",
startup:{NG:250000}, profit:{NG:100000},
comp:"Banks, VTU apps", 
beat:"NEPA, DSTV, Data, School fees in one place", 
limit:"Network + Low margin", 
mistake:"No other service to upsell"},

{id:"insurance",name:"Insurance Agent",cat:"Finance",summary:"₦250k-₦800k/month commissions",
startup:{NG:100000}, profit:{NG:200000},
comp:"Leadway, AIICO", 
beat:"Health + Car + Life insurance + Installment", 
limit:"People no dey trust insurance + CAC", 
mistake:"Not following up clients"},

{id:"bdc",name:"Bureau De Change",cat:"Finance",summary:"₦1m-₦4m/month forex",
startup:{NG:10000000}, profit:{NG:1200000},
comp:"Banks, Other BDCs", 
beat:"Best rate + Airport + Hotels", 
limit:"CBN license + EFCC + Dollar scarcity", 
mistake:"No security"},

{id:"savings",name:"Cooperative Savings",cat:"Finance",summary:"₦500k-₦2m/month managing",
startup:{NG:150000}, profit:{NG:250000},
comp:"Banks, Esusu apps", 
beat:"Market association + Low interest loans", 
limit:"Defaulters + Record keeping", 
mistake:"No constitution and rules"},

{id:"remittance",name:"Money Transfer Agent",cat:"Finance",summary:"₦300k-₦900k/month diaspora",
startup:{NG:800000}, profit:{NG:350000},
comp:"Western Union, MoneyGram", 
beat:"Faster + Lower fees + Doorstep delivery", 
limit:"CBN license + Fraud", 
mistake:"No verification process"},

{id:"tax",name:"Tax Filing Service",cat:"Finance",summary:"₦200k-₦600k/month SMEs",
startup:{NG:200000}, profit:{NG:180000},
comp:"Accountants", 
beat:"CAC + FIRS + State tax in one package", 
limit:"Government policy change", 
mistake:"Not getting certified"},

{id:"wallet",name:"Digital Wallet Reseller",cat:"Finance",summary:"₦100k-₦400k/month VTU",
startup:{NG:300000}, profit:{NG:120000},
comp:"Opay, PalmPay", 
beat:"Referral bonus + Agent network", 
limit:"App downtime + Low margin", 
mistake:"Depending on one fintech"}
];
