const BUSINESS_DATA = [
{"id":"shawarma","name":"Shawarma Stand","cat":"Food","summary":"₦500k-₦1.2m/month near schools","startup":{"NG":800000},"profit":{"NG":350000},"comp":"The Place, Chicken Republic","beat":"Late night hours + Student discount + Delivery","limit":"NEPA + Meat price increase + NAFDAC","mistake":"Bad location with no foot traffic"},
{"id":"amala","name":"Amala & Ewedu Joint","cat":"Food","summary":"₦300k-₦800k/month daily customers","startup":{"NG":600000},"profit":{"NG":250000},"comp":"Mama Put, Bukas","beat":"Clean environment + Fast service + Soup variety","limit":"Perishable food + Staff wahala","mistake":"Cooking too much and wasting food"},
{"id":"smallchops","name":"Small Chops Business","cat":"Food","summary":"₦200k-₦600k/month events","startup":{"NG":250000},"profit":{"NG":180000},"comp":"Event caterers","beat":"Instagram + Free delivery + Party packages","limit":"Last minute orders + Ingredient cost","mistake":"Not collecting 50% deposit"},
{"id":"zobo","name":"Zobo & Tigernut Drink","cat":"Food","summary":"₦150k-₦400k/month wholesale","startup":{"NG":150000},"profit":{"NG":120000},"comp":"Chi, 5 Alive","beat":"No sugar + Bottled + Supply to gyms","limit":"Short shelf life + Bottles cost","mistake":"Poor hygiene and packaging"},
{"id":"buka","name":"Mama Put Buka","cat":"Food","summary":"₦800k-₦2m/month daily rice","startup":{"NG":1200000},"profit":{"NG":450000},"comp":"Local bukas","beat":"Clean plates + Free water + Faster service","limit":"Food waste + Staff theft + NEPA","mistake":"Not counting food daily"},
{"id":"premiumshawarma","name":"Premium Shawarma","cat":"Food","summary":"₦600k-₦1.5m/month malls","startup":{"NG":1500000},"profit":{"NG":500000},"comp":"The Place, Dominos","beat":"Better bread + Chicken chunks + Delivery app","limit":"Rent + Ingredient cost","mistake":"Bad location in low traffic area"},
{"id":"suya","name":"Suya Spot","cat":"Food","summary":"₦400k-₦1m/month nights","startup":{"NG":500000},"profit":{"NG":300000},"comp":"Street suya guys","beat":"Cleaner + Packaged + Spicy options","limit":"Meat price + Security","mistake":"No license from local govt"},
{"id":"meatpie","name":"Meat Pie Bakery","cat":"Food","summary":"₦300k-₦700k/month schools","startup":{"NG":400000},"profit":{"NG":200000},"comp":"Mr Biggs","beat":"Bigger size + Doorstep delivery","limit":"Flour price + Oven NEPA","mistake":"Making too many and it gets stale"},
{"id":"icecream","name":"Ice Cream Parlor","cat":"Food","summary":"₦500k-₦1.2m/month kids","startup":{"NG":2000000},"profit":{"NG":350000},"comp":"Cold Stone","beat":"Nigerian flavors + Cheaper price","limit":"Freezer NEPA + Melt","mistake":"Buying big freezer without customers"},
{"id":"cake","name":"Cake & Bakery","cat":"Food","summary":"₦700k-₦2m/month events","startup":{"NG":1000000},"profit":{"NG":400000},"comp":"Local bakers","beat":"Instagram + Same day delivery","limit":"Last minute orders + Ingredient","mistake":"Not collecting deposit"},
{"id":"peppersoup","name":"Pepper Soup Joint","cat":"Food","summary":"₦400k-₦900k/month night life","startup":{"NG":700000},"profit":{"NG":280000},"comp":"Beer parlours","beat":"Goat meat + Fresh fish + Lounge vibe","limit":"Meat price + Police wahala","mistake":"No security"},
{"id":"fishgrill","name":"Fish Grill Business","cat":"Food","summary":"₦350k-₦800k/month weekends","startup":{"NG":600000},"profit":{"NG":250000},"comp":"Bukka, Mama Put","beat":"Tilapia + Croaker + Delivery","limit":"Fish scarcity + Smoke","mistake":"Bad location far from road"},
{"id":"sharwama2","name":"Premium Shawarma","cat":"Food","summary":"₦600k-₦1.5m/month malls","startup":{"NG":1500000},"profit":{"NG":500000},"comp":"The Place, Dominos","beat":"Better bread + Chicken chunks + Delivery app","limit":"Rent + Ingredient cost","mistake":"Bad location in low traffic area"},
{"id":" suya","name":"Suya Spot","cat":"Food","summary":"₦400k-₦1m/month nights","startup":{"NG":500000},"profit":{"NG":300000},"comp":"Street suya guys","beat":"Cleaner + Packaged + Spicy options","limit":"Meat price + Security","mistake":"No license from local govt"}
];
